spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:${config-server.config-folder:./config-repo}
#On Windows, you need an extra "/" in the file URL if it is absolute with a drive prefix (for example,file:///${user.home}/config-repo).
